version: '3'
services:
  redis:
    image: redis
    container_name: redis
    network_mode: "host"
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    container_name: mongodb
    network_mode: "host"
    ports:
      - 27017:27017

  mysql:
    image: mysql
    container_name: mysql
    network_mode: "host"
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=fiap-persistencepwd"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: "host"
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - "RABBITMQ_DEFAULT_USER=rabbit-usr"
      - "RABBITMQ_DEFAULT_PASS=rabbit-pwd"

  fiap_sample_login:
    image: fiap.sample.login
    container_name: 'fiap.sample.login'
    network_mode: "host"
    environment:
      - "MONGO_DB_HOST=localhost"
      - "MONGO_DB_PORT=27017"
      - "MONGO_DB_DATABASE=fiapSampleLogin"
      - "REDIS_HOST=localhost"
      - "REDIS_PORT=6379"
      - "REDIS_PASSWORD="
    restart: on-failure
    depends_on:
      - redis
      - mongodb

  fiap_stock_mgnt:
    image: fiap.stock.mgnt
    container_name: 'fiap.stock.mgnt'
    network_mode: "host"
    environment:
      - "MYSQL_JDBC_URL=jdbc:mysql://localhost:3306/stock?createDatabaseIfNotExist=true"
      - "MYSQL_USER_NAME=root"
      - "MYSQL_PASSWORD=fiap-persistencepwd"
      - "RABBIT_MQ_HOST=localhost"
      - "RABBIT_MQ_PORT=5672"
      - "RABBIT_MQ_USER_NAME=rabbit-usr"
      - "RABBIT_MQ_PASSWORD=rabbit-pwd"
    restart: on-failure
    depends_on:
      - mysql
      - rabbitmq

  fiap_stock_portal:
    image: fiap.stock.portal
    container_name: 'fiap.stock.portal'
    network_mode: "host"
    ports:
      - 8383:8383
    restart: on-failure
    depends_on:
      - redis
      - mongodb
      - rabbitmq
