version: '3'
services:
  fiap_stock_portal_front:
    image: fiap.stock.portal.front
    container_name: 'fiap.stock.portal.front'
    network_mode: "host"
    environment:
      - "FIAP_SAMPLE_LOGIN_BACKEND_HOST=localhost"
      - "FIAP_SAMPLE_LOGIN_BACKEND_PORT=8181"
      - "FIAP_STOCK_PORTAL_BACKEND_HOST=localhost"
      - "FIAP_STOCK_PORTAL_BACKEND_PORT=8383"

  fiap_stock_mgnt_front:
    image: fiap.stock.mgnt.front
    container_name: 'fiap.stock.mgnt.front'
    network_mode: "host"
    environment:
      - "FIAP_SAMPLE_LOGIN_BACKEND_HOST=localhost"
      - "FIAP_SAMPLE_LOGIN_BACKEND_PORT=8181"
      - "FIAP_STOCK_MGNT_BACKEND_HOST=localhost"
      - "FIAP_STOCK_MGNT_BACKEND_PORT=8282"