server:
  port: 8383

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fiapStockPortal
  main:
    banner-mode: console

logging:
  config: classpath:logback.xml

stock:
  mgnt:
    host: http://localhost:8282/

redis:
  host: localhost
  port: 6379
  password: