spring:
  data:
    mongodb:
      host: localhost

logging:
  config: classpath:logback-local.xml

redis:
  host: localhost
  port: 6379
  password:

rabbitmq:
  host: localhost
  port: 5672
  username: rabbit-usr
  password: rabbit-pwd
  virtual-host: '/'