server:
  port: 8383

spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: fiapStockPortal
  main:
    banner-mode: console

logging:
  config: classpath:logback.xml

redis:
  host: 0.0.0.0
  port: 6379
  password:

rabbitmq:
  host: 0.0.0.0
  port: 5672
  username: rabbit-usr
  password: rabbit-pwd
  virtual-host: '/'