server:
  port: 8383

spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: fiapStockPortal
  main:
    banner-mode: console

logging:
  config: classpath:logback.xml

stock:
  mgnt:
    host: http://0.0.0.0:8282/

redis:
  host: 0.0.0.0
  port: 6379
  password: