server:
  port: 8181

spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: fiapSampleLogin
  main:
    banner-mode: console

logging:
  config: classpath:logback.xml

redis:
  host: 0.0.0.0
  port: 6379
  password: