server:
  port: 8181

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      database: ${MONGO_DB_DATABASE}
  main:
    banner-mode: console

logging:
  config: classpath:logback.xml

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}