server:
  port: 8282

spring:
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback.xml

rabbitmq:
  host: ${RABBIT_MQ_HOST}
  port: ${RABBIT_MQ_PORT}
  username: ${RABBIT_MQ_USER_NAME}
  password: ${RABBIT_MQ_PASSWORD}
  virtual-host: '/'