server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/stock?createDatabaseIfNotExist=true
    username: root
    password: fiap-persistencepwd
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback.xml

stock:
  portal:
    host: http://0.0.0.0:8383/

rabbitmq:
  host: 0.0.0.0
  port: 5672
  username: rabbit-usr
  password: rabbit-pwd
  virtual-host: '/'