spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock?createDatabaseIfNotExist=true

logging:
  config: classpath:logback-local.xml

rabbitmq:
  host: localhost
  port: 5672
  username: rabbit-usr
  password: rabbit-pwd
  virtual-host: '/'